export enum Mensajes {
    tituloSuccess = 'Éxito',
    tituloWarning = 'Advertencia',
    tituloError = "Error",
    tituloInfo = 'Info',
    tituloFaltanDatos = 'Faltan datos',
    tituloDatosErroneos = 'Datos erróneos',
    tituloDatosRepetidos = 'Datos repetidos',
    mensajeGuardadoSuccess = 'Datos guardados con éxito',
    mensajeActualizadoSuccess = 'Datos actualizados con éxito',
    mensajeErrorGenerico = 'Error al ejecutar la acción',
    mensajeErrorLectura = 'Error al querer obtener la información',
    mensajeErrorCreacion = 'Error al querer crear el registro',
    mensajeErrorActualizacion = 'Error al querer actualizar el registro',
    mensajeErrorDescargaArchivo = 'Hubo un error al querer descargar el archivo',
    mensajeValidacionDatoFaltanteInputs = 'Debe ingresar ',
    mensajeValidacionDatoFaltanteSelects = 'Debe seleccionar ',
    nuevoBoton = 'Nuevo',
    editarBoton = 'Editar',
    cancelarBoton = 'Cancelar',
    guardarBoton = 'Guardar',
    filtrarBoton = 'Filtrar',
    limpiarFiltrosBoton = 'Limpiar',
    anularBoton = 'Anular',
    reporteBoton = 'Reporte'
}